[package]
name = "approach2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
rand = "0.8.5"
rand_pcg = "0.3.1"
